//	@file Version: 1.0
//	@file Name: serverVars.sqf
//	@file Author: [404] Deadbeat
//	@file Created: 20/11/2012 05:19
//	@file Args: 

diag_log format["WASTELAND SERVER - Initilizing Server Vars"];

CVG_weapons = [];
CVG_weapons = CVG_rifles;
CVG_weapons = CVG_weapons + CVG_Scoped;
CVG_weapons = CVG_weapons + CVG_Heavy;
CVG_weapons = CVG_weapons + CVG_pistols;
CVG_weapons = CVG_weapons + CVG_Launchers;

sideMissionPos = "";
mainMissionPos = "";

currentVehicles = [];
publicVariable "currentVehicles";
pvar_teamSwitchList = [];
publicVariable "pvar_teamSwitchList";
pvar_teamKillList = [];
publicVariable "pvar_teamKillList";
pvar_beaconListBlu = []; 
publicVariable "pvar_beaconListBlu";
pvar_beaconListRed = []; 
publicVariable "pvar_beaconListRed";
pvar_beaconListInd = [];
publicVariable "pvar_beaconListInd";
clientMissionMarkers = [];
publicVariable "clientMissionMarkers";
clientRadarMarkers = [];
publicVariable "clientRadarMarkers";
currentDate = [];
publicVariable "currentDate";
currentInvites = [];
publicVariable "currentInvites";
currentBounties = [];
publicVariable "currentBounties";
//Bounty List array
//pvar_bountyList = [];
//publicVariable "pvar_bountyList";
	
if (isServer) then {
	"PlayerCDeath" addPublicVariableEventHandler {_id = (_this select 1) spawn server_playerDied};
};

currentStaticHelis = []; // Storage for the heli marker numbers so that we don't spawn wrecks on top of live helis

//Civilian Vehicle List - Random Spawns
civilianVehicles = ["HMMWV",                                   
                    "UAZ_CDF",
					"UAZ_RU",
					"LandRover_TK_CIV_EP1",
					"UAZ_Unarmed_TK_CIV_EP1",
                    "Ural_INS",
                    "SUV_TK_EP1",
                    "V3S_Open_TK_EP1",								
					"LandRover_CZ_EP1",
					"V3S_TK_GUE_EP1",
					"UralOpen_CDF",									
					"LandRover_Special_CZ_EP1",
					"Old_moto_TK_Civ_EP1",
					"ATV_CZ_EP1",								
					"M1030_US_DES_EP1",	
					"Lada2_TK_CIV_EP1",
					"SUV_PMC",								
					"S1203_TK_CIV_EP1", 
					"TT650_TK_CIV_EP1",
					"Volha_1_TK_CIV_EP1", 
					"Lada1",
					"Skoda",  
					"TT650_Gue", 
					"car_hatchback", 
					"datsun1_civil_1_open", 
					"datsun1_civil_2_covered", 
					"hilux1_civil_2_covered",
					"hilux1_civil_1_open",	
                    "Pickup_PK_GUE",
					"UralCivil",
					"SkodaGreen",
					"VWGolf",
					"BAF_Offroad_W"];

//Military Vehicle List - Random Spawns
militaryVehicles = ["BTR40_TK_INS_EP1",
					"BTR40_MG_TK_INS_EP1",
					"BAF_Jackal2_GMG_W",
					"BAF_Jackal2_L2A1_D",
					"BAF_Jackal2_GMG_W",
					"BAF_Jackal2_L2A1_D",
					"ArmoredSUV_PMC",
					"Offroad_DSHKM_Ins",
					"UAZ_MG_INS",
					"Pickup_PK_TK_GUE_EP1",
					"UAZ_SPG9_INS",
					"UAZ_AGS30_RU",
					"Offroad_SPG9_TK_GUE_EP1",
					"LandRover_MG_TK_INS_EP1",
					"LandRover_SPG9_TK_EP1",
					"HMMWV_MK19",
					"HMMWV_M2",
					"HMMWV_Armored",
					"HMMWV_TOW",
					"HMMWV_Ambulance",
					"HMMWV_M998A2_SOV_DES_EP1",	
					"SUV_UN_EP1"];

//Armed Military Vehicle List - Random Spawns
armedMilitaryVehicles = ["BMP2_Ambul_CDF",
						"LAV25",
						"BTR90_HQ",
						"HMMWV_Avenger",
						"BRDM2_TK_EP1",
						"BRDM2_HQ_Gue",
						"BRDM2_ATGM_TK_EP1",
						"BTR60_TK_EP1",
						"M1126_ICV_MK19_EP1",
						"M1126_ICV_M2_EP1",
						"M1135_ATGMV_EP1",
						"GAZ_Vodnik_HMG",
						"GAZ_Vodnik_MedEvac",
						"GAZ_Vodnik"];
							
//Panzer Vehicle List - Random Spawns
panzerVehicles = [			"BMP2_TK_EP1",
							"BMP2_UN_EP1",
							"BMP2_HQ_TK_EP1",
							"T34_TK_EP1",
							"T34_TK_GUE_EP1",
							"M113_TK_EP1",
							"M113_UN_EP1",
							"M113Ambul_UN_EP1",
							"M2A2_EP1",
							"M2A3_EP1",
							"M6_EP1",
							"BMP2_CDF",
							"BMP2_INS",
							"BMP2_Ambul_INS",
							"BMP2_HQ_CDF",
							"BMP2_HQ_INS",
							"BMP3"];							

//Item Config
pickupList = [				"Satelit",
							"Fuel_can"];

//Object List - Random Spawns.
objectList = [				"M2StaticMG",
                            "KORD_high_UN_EP1",
                            "Base_WarfareBBarrier10xTall",
                            "Base_WarfareBBarrier10x",
                            "Base_WarfareBBarrier5x",
                            "Land_Barrel_water",
                            "Suitcase",
                            "Fuel_can",
                            "Land_Fire_barrel_burning",
                            "Land_fort_bagfence_corner",
                            "Land_BagFenceLong",
                            "Land_Fort_Watchtower_EP1",
                            "Land_Fort_Watchtower",
                            "Land_HBarrier_large",
                            "Land_HBarrier5",
                            "Land_HBarrier3",
                            "Land_ladder",
                            "Land_ladder_half",
                            "Land_CncBlock_Stripes",
                            "Misc_Cargo1B_military",
                            "Barrack2",
                            "CDF_WarfareBFieldhHospital",
                            "Land_RedWhiteBarrier",
                            "RoadBarrier_long",
                            "Land_vez",
                            "ZavoraAnim",
                            "Land_radar_EP1",
                            "Land_CncBlock",
                            "Land_fort_bagfence_long",
                            "Land_Misc_ConcPipeline_EP1",
                            "Fort_Barricade",
                            "Land_fort_rampart",
                            "Land_fortified_nest_small",
                            "Land_fort_bagfence_round",
                            "Land_fortified_nest_big",
                            "Land_fort_bagfence_long",
                            "Land_stand_small_EP1",
                            "Land_Misc_deerstand",
                            "WarfareBDepot",
                            "USMC_WarfareBMGNest_M240",
                            "Hedgehog",
                            "Land_GuardShed",
                            "TOW_TriPod_US_EP1",
                            "MASH",
                            "Land_CamoNet_NATO",
                            "Land_tent_east"];
                                         
//Object List - Random Spawns.
staticWeaponsList = ["ZU23_CDF",
					"Stinger_Pod",
					"AGS_CDF",
					"Igla_aa_pod_east"];

//Object List - Random Helis.
staticHeliList = ["MH60S",
				"Mi17_CDF",
                "Mi17_INS",
                "Mi17_medevac_CDF",
                "Mi17_medevac_Ins",
                "Mi17_medevac_RU",
                "Mi17_rockets_RU",
                "UH1Y",
                "MV22",
                "UH60M_EP1",
                "UH60M_MEV_EP1",
                "AH6J_EP1",
                "AH6X_EP1",
                "MH6J_EP1",
                "CH_47F_EP1",
                "CH_47F_BAF",
                "Mi17_TK_EP1",
                "Mi17_UN_CDF_EP1",
                "Mi171Sh_CZ_EP1",
                "Mi171Sh_rockets_CZ_EP1",
                "UH1H_TK_EP1",
                "UH1H_TK_GUE_EP1",
                "BAF_Merlin_HC3_D"];

//Random Weapon List - Change this to what you want to spawn in cars.
vehicleWeapons = ["AK_107_GL_kobra",
				"AK_107_kobra",
				"M4SPR",
				"FN_FAL_ANPVS4",
				"SMAW",
				"Strela",
				"M110_NVG_EP1",
				"BAF_L110A1_Aim",
				"BAF_L7A2_GPMG",
				"BAF_L85A2_RIS_ACOG",
				"M32_EP1",
				"MP5SD",
				"G36_C_SD_camo",
				"M4A3_RCO_GL_EP1",
				"SCAR_L_STD_Mk4CQT",
				"Javelin",
				"Saiga12K",
				"M8_SAW",
				"M8_compact",
				"DMR",
				"M8_sharpshooter",
				//"m107_TWS_EP1",
				"M24_des_EP1",
				//"M110_TWS_EP1",
				"UZI_SD_EP1",
				"Huntingrifle",
				"M40A3",
				"M4A1_HWS_GL_camo",
				"BAF_LRR_scoped_W",
				"G36_C_SD_eotech",
				//"m8_tws_sd",
				"MakarovSD",
				"M4A1_HWS_GL_SD_Camo",
				"M14_EP1",
				"SCAR_H_LNG_Sniper_SD",
				"M4A3_RCO_GL_EP1",
				"M240",
				"M249",
				"M4A1_RCO_GL",
				"M4A1_HWS_GL",
				"M4A3_CCO_EP1",
				"M60A4_EP1",
				"m8_carbine",
				"MG36",
				"Mk_48",
				"SCAR_L_STD_EGLM_RCO",
				//"M249_TWS_EP1",
				"SCAR_L_CQC_EGLM_Holo",
				"SCAR_H_STD_EGLM_Spect",
				"SCAR_H_CQC_CCO",
				//"SCAR_L_STD_EGLM_TWS",
				"Igla",
				"Javelin",
				"Stinger",
				"M136",
				"MetisLauncher",
				"RPG7V",
				"RPG18",
				"SMAW",
				"Strela"];
                
blacklist = ["Land_stand_small_EP1",
		"Land_stand_meat_EP1",
		"Land_stand_waterl_EP1",
		"Land_Crates_stack_EP1",
		"Land_Carpet_rack_EP1",
		"Land_Market_stalls_01_EP1",
		"Land_Market_stalls_02_EP1",
		"Land_Market_shelter_EP1",
		"Land_Misc_Well_L_EP1",
		"Land_Misc_Well_C_EP1",
		"Fort_StoneWall_EP1",
		"Land_Wall_L_2m5_gate_EP1",
		"Land_Wall_L1_gate_EP1",
		"Land_Wall_L3_gate_EP1",
		"Land_Wall_L3_5m_EP1",
		"Land_Wall_L3_pillar_EP1",
		"Land_Wall_L_Mosque_1_EP1",
		"Land_Wall_L_Mosque_2_EP1",
		"Wall_FenW2_6_EP1",
		"Wall_L_2m5_EP1",
		"Wall_L1_2m5_EP1",
		"Wall_L1_5m_EP1",
		"Wall_L2_5m_EP1",
		"Wall_L3_5m_EP1",
		"Land_BoatSmall_1",
		"Land_D_Mlyn_Vys",
		"Land_D_Pec_Vez1",
		"Land_Ind_BoardsPack1",
		"Land_Ind_Shed_02_end",
		"Land_Ind_Shed_01_end",
		"Land_Ind_Shed_01_main",
		"Land_Ind_BoardsPack2",
		"Land_Dam_Barrier_40",
		"Land_Dam_ConcP_20",
		"Land_Dam_Conc_20",
		"Land_D_Pec_Vez2",
		"Land_BoatSmall_2a",
		"Land_BoatSmall_2b",
		"Land_fort_artillery_nest",
		"Land_fort_rampart",
		"Land_Vez_Pec",
		"Land_runway_edgelight",
		"Land_Nav_Boathouse_PierR",
		"Land_Nav_Boathouse_PierT",
		"Land_Nav_Boathouse_PierL",
		"Land_fort_bagfence_corner",
		"Land_fort_bagfence_long",
		"Land_fort_bagfence_round",
		"Land_Fort_Watchtower",
		"Land_NavigLight",
		"Land_Panelak",
		"Land_Panelak2",
		"Land_Panelak3",
		"Land_plot_green_branka",
		"Land_plot_rust_branka",
		"Land_plot_green_vrata",
		"Land_plot_rust_vrata",
		"Land_plot_istan1_rovny_gate",
		"Land_Plot_Ohrada_Pruchozi",
		"Land_plot_zboreny",
		"Land_plot_zed_drevo1_branka",
		"Land_psi_bouda",
		"Land_A_Castle_Bastion",
		"Land_A_Castle_Gate",
		"Land_A_Castle_Wall1_20",
		"Land_A_Castle_Wall1_20_Turn",
		"Land_A_Castle_Wall1_Corner",
		"Land_A_Castle_Wall1_End",
		"Land_A_Castle_Wall1_End_2",
		"Land_A_Castle_Wall2_30",
		"Land_A_Castle_Wall2_Corner",
		"Land_A_Castle_Wall2_End",
		"Land_A_Castle_Wall2_End_2",
		"Land_A_Castle_WallS_10",
		"Land_Gate_wood2_5",
		"Land_Ind_Expedice_2",
		"Land_Ind_Expedice_3",
		"Land_Ind_Timbers",
		"Land_Rail_Semafor",
		"Land_Rail_Zavora",
		"Land_Stoplight02",
		"Land_Wall_CBrk_5_D",
		"Land_brana02nodoor",
		"Land_plot_green_branka",
		"Land_plot_rust_branka",
		"Land_plot_green_vrata",
		"Land_molo_drevo_bs",
		"Land_molo_drevo_end",
		"Land_nav_pier_m_2",
		"Land_psi_bouda",
		"Land_plot_rust_vrata",
		"Land_rails_bridge_40",
		"Land_seno_balik",
		"Land_sloup_vn",
		"Land_sloup_vn_drat",
		"Land_sloup_vn_dratZ",
		"Land_sloup_vn_drat_d",
		"ZavoraAnim",
		"Land_vez",
		"Land_pumpa",
		"Land_Gate_Wood1_5",
		"Land_fortified_nest_big",
		"Land_fortified_nest_small",
		"Fort_Nest",
		"Land_Fire",
		"Land_Fire_barrel",
		"Land_Fire_barrel_burning",
		"Land_Fire_burning",
		"Land_Campfire",
		"Land_Campfire_burning",
		"Misc_TyreHeap",
		"Land_ConcreteBlock",
		"Land_ConcreteRamp",
		"Land_sign_altar",
		"Land_Sign_Bar_RU",
		"Land_Sign_BES",
		"Land_sign_TEC",
		"Land_sign_ulgano",
		"Land_SignB_Gov",
		"Land_SignB_GovPolice",
		"Land_SignB_GovSchool",
		"Land_SignB_GovSign",
		"Land_SignB_Hotel_CZ",
		"Land_SignB_Hotel_CZ2",
		"Land_SignB_Hotel_CZ3",
		"Land_SignB_Pharmacy",
		"Land_SignB_PostOffice",
		"Land_SignB_Pub_CZ1",
		"Land_SignB_Pub_CZ2",
		"Land_SignB_Pub_CZ3",
		"Land_SignB_Pub_RU1",
		"Land_SignB_Pub_RU2",
		"Land_SignB_Pub_RU3",
		"Land_Ind_Timbers",
		"Haystack",
		"Pile_of_wood",
		"Land_IndPipe1_stair",
		"Land_IndPipe1_stair_todo_delete",
		"Land_IndPipe2_big_9",
		"Land_IndPipe2_big_18",
		"Land_IndPipe2_big_18ladder",
		"Land_IndPipe2_big_support",
		"Land_IndPipe2_bigL_R",
		"Land_IndPipe2_bigL_L",
		"Land_IndPipe2_bigBuild1_R",
		"Land_IndPipe2_bigBuild1_L",
		"Land_IndPipe2_bigBuild2_R",
		"Land_IndPipe2_bigBuild2_L",
		"Land_IndPipe2_big_ground1",
		"Land_IndPipe2_big_ground2",
		"Land_IndPipe2_T_R",
		"Land_IndPipe2_T_L",
		"Land_IndPipe2_Small_9",
		"Land_IndPipe2_Small_ground1",
		"Land_IndPipe2_Small_ground2",
		"Land_IndPipe2_SmallBuild1_L",
		"Land_IndPipe2_SmallBuild1_R",
		"Land_IndPipe2_SmallBuild2_L",
		"Land_IndPipe2_SmallBuild2_R",
		"Land_IndPipe2_SmallL_L",
		"Land_IndPipe2_SmallL_R",
		"Land_nav_pier_m_2",
		"land_nav_pier_c",
		"land_nav_pier_c2",
		"land_nav_pier_c2_end",
		"land_nav_pier_c_270",
		"land_nav_pier_c_90",
		"land_nav_pier_c_big",
		"land_nav_pier_C_L",
		"land_nav_pier_C_L10",
		"land_nav_pier_C_L30",
		"land_nav_pier_C_R",
		"land_nav_pier_C_R10",
		"land_nav_pier_C_R30",
		"land_nav_pier_c_t15",
		"land_nav_pier_c_t20",
		"land_nav_pier_F_17",
		"land_nav_pier_F_23",
		"land_nav_pier_m",
		"land_nav_pier_m_1",
		"land_nav_pier_m_end",
		"land_nav_pier_M_fuel",
		"land_nav_pier_pneu",
		"Land_ruin_chimney",
		"Land_ruin_corner_1",
		"Land_ruin_corner_2",
		"Land_ruin_rubble",
		"Land_ruin_walldoor",
		"Land_ruin_wall",
		"land_nav_pier_uvaz",
		"Land_Misc_Cargo1C",
		"Land_Misc_Cargo1D",
		"Land_Misc_Cargo1E",
		"Land_Misc_Cargo1F",
		"Land_Misc_Cargo1G",
		"Land_Misc_Cargo2B",
		"Land_Misc_Cargo2C",
		"Land_Misc_Cargo2D",
		"Land_Misc_Cargo2E",
		"Land_Misc_deerstand",
		"Land_Misc_GContainer_Big",
		"Land_sign_elektrozavodsk",
		"Land_sign_balota",
		"Land_sign_berezino",
		"Land_sign_chernogorsk",
		"Land_sign_kamenka",
		"Land_sign_kamyshovo",
		"Land_sign_komarovo",
		"Land_sign_prigorodki",
		"Land_sign_solnichnyi",
		"Land_wagon_box",
		"Land_wagon_flat",
		"Land_wagon_tanker",
		"Land_Wall_CBrk_5_D",
		"Land_Wall_CGry_5_D",
		"Land_Wall_Gate_Ind1_L",
		"Land_Wall_Gate_Ind1_R",
		"Land_Gate_IndVar2_5",
		"Land_Gate_wood1_5",
		"Land_Gate_wood2_5",
		"Land_Wall_Gate_Ind2A_R",
		"Land_Wall_Gate_Ind2B_R",
		"Land_Wall_Gate_Ind2Rail_R",
		"Land_Wall_Gate_Village",
		"Land_Wall_Gate_Wood1",
		"Land_Wall_Gate_Ind2A_L",
		"Land_Wall_Gate_Ind2B_L",
		"Land_Wall_Gate_Ind2Rail_L"];