if(!hasInterface)exitwith{};
#include "functions\ckbl.sqf"[]spawn{disableSerialization;waitUntil{!isNull player};waituntil{!(IsNull(findDisplay 46))};private["_sclp","_qddz","_happ","_qrjq","_afab",'_friendlyIcon'];_qddz=objNull;qptp=false;(findDisplay 46)displayAddEventHandler["KeyDown","
		if ( (_this select 1) == 219 ) then {
			qptp = true;
		};
	"];(findDisplay 46)displayAddEventHandler["KeyUp","
		if ( (_this select 1) == 219 ) then {
			qptp = false;
		};
	"];ggwd=call{private"_gpde";_gpde=toArray str missionConfigFile;_gpde resize(count _gpde - 15);toString _gpde};qbfa=ggwd+"client\systems\hud\icons\friendly.paa";mxfd=playerSide call dxob;mgwf=format["<img image='%1' color='%2' size='1'/>",qbfa,mxfd call zyjx];_sclp={11 cutRsc['HUDRsc','PLAIN'];_qddz=uiNamespace getVariable'HUD';_happ=_qddz displayCtrl HUDplayerInfoIDC;_qrjq=_qddz displayCtrl HUDserverInfoIDC;_afab=_qddz displayCtrl HUDvehicleInfoIDC;(_qddz displayCtrl HUDnotificationIDC)ctrlShow false;(_qddz displayCtrl HUDnotificationTextIDC)ctrlShow false;(_qddz displayCtrl HUDnotificationIconIDC)ctrlShow false;_qrjq ctrlSetStructuredText parseText('HUDServerInfo'call bdra)};private["_saon","_wahl","_cdqe","_dwjl","_qbsp","_aswn"];_saon=missionConfigFile>>"RscTitles">>"HUDRsc";_wahl=getNumber(_saon>>"controlsBackground">>"vehicleInfo">>"sizeEx");_cdqe=getNumber(_saon>>"controlsBackground">>"vehicleInfo">>"x");_dwjl=getNumber(_saon>>"controlsBackground">>"vehicleInfo">>"y");_qbsp=getNumber(_saon>>"controlsBackground">>"vehicleInfo">>"w");_aswn=getNumber(_saon>>"controlsBackground">>"vehicleInfo">>"h");oask=objNull;(findDisplay 12 displayCtrl 51)ctrlAddEventHandler["MouseMoving","_this call tjti"];(findDisplay 12 displayCtrl 51)ctrlAddEventHandler["Draw","_this call qvgz"];[]spawn{disableSerialization;_seqm='banners'call bdra;_sglx=(uiNamespace getVariable'HUD')displayCtrl HUDbannerIDC;_sglx ctrlSetFade 0;_sglx ctrlCommit 0;while{true}do{{_sglx=(uiNamespace getVariable'HUD')displayCtrl HUDbannerIDC;_sglx ctrlSetText(_x select 0);_sglx ctrlSetFade 0;_sglx ctrlCommit 3;sleep(_x select 1);_sglx ctrlSetFade 1;_sglx ctrlCommit 3;sleep(_x select 2);while{(vehicle player)!=player}do{sleep 5};nil}count _seqm}};[]spawn{waitUntil{[]call bymd;false}};[]spawn{disableSerialization;private["_ggee","_qrjq"];_ggee=vehicle player;_qrjq=missionConfigFile>>"RscTitles">>"HUDRsc">>"controlsBackground">>"serverInfo";_fxad=getNumber(_qrjq>>"w");_eiop=getNumber(_qrjq>>"h");_zsbn=uiNamespace getVariable'HUD';while{true}do{waitUntil{_ggee!=vehicle player||(uiNamespace getVariable'HUD')!=_zsbn};_ggee=vehicle player;_zsbn=uiNamespace getVariable'HUD';_x=getNumber(_qrjq>>"x");_qpjd=getNumber(_qrjq>>"y");if!(_ggee isKindOf"Man")then{if(getNumber(configFile>>"CfgVehicles">>(typeOf _ggee)>>"radarType")>0)then{_x=safezoneX+0.078+(0.161*SafezoneH);_qpjd=safezoneY+0.035}else{_x=safezoneX+0.078}};((uiNamespace getVariable'HUD')displayCtrl HUDserverInfoIDC)ctrlSetPosition[_x,_qpjd,_fxad,_eiop];((uiNamespace getVariable'HUD')displayCtrl HUDserverInfoIDC)ctrlCommit 0}};private["_sreo","_ekwk","_abhp","_damagePercent","_kezg"];while{true}do{if(isNull _qddz&&isNull(uiNamespace getVariable['rogy',displayNull])&&isNil"bis_fnc_camera_cam"&&!visibleMap)then{[]call _sclp}else{if!(isNull(uiNamespace getVariable['rogy',displayNull])&&isNil"bis_fnc_camera_cam"&&!visibleMap)then{11 cutText["","PLAIN"]}};_happ ctrlSetStructuredText parseText format['
		<img image="client\systems\hud\icons\health.paa" size="0.8" /> <t shadow="2">%2%1</t><br />
		<img image="client\systems\hud\icons\compass.paa" size="0.8" /> <t shadow="2">%3°</t>
		','%',round(100-(damage player)*100),round((eyeDirection player)call umun)];if(vehicle player!=player)then{_afab ctrlShow true;_tcuz="";{_sreo=(assignedVehicleRole _x);_ekwk="";if(count _sreo==0)then{_sreo=['Cargo']};_ekwk=(_sreo select 0)call{if(_this=="Cargo")exitwith{"\ca\ui\data\cmdbar_cargo_ca.paa"};if(_this=="Driver")exitwith{"\ca\ui\data\cmdbar_driver_ca.paa"};if(_this=="Turret")exitwith{"\ca\ui\data\cmdbar_gunner_ca.paa"};"\ca\ui\data\cmdbar_cargo_ca.paa"};_abhp="";if(alive _x)then{_abhp=[1,(1- damage _x),(1- damage _x),1]call zyjx}else{_abhp="#000000"};_tcuz=_tcuz+format['
					<t shadow="2" color="%3">%1</t> <img image="%2" size="0.8" /><br />
					',name _x,_ekwk,_abhp]}count(crew vehicle player);_afab ctrlSetStructuredText parseText format['<t align="right">%1</t>',_tcuz];_kezg=_wahl*(count crew vehicle player);_afab ctrlSetPosition[_cdqe,_dwjl+(_aswn - _kezg),_qbsp,_kezg];_afab ctrlCommit 0}else{_afab ctrlShow false};sleep 0.05}};