#define CONFIG_INDEX_CLASS 0
#define CONFIG_INDEX_CAPACITY 1
#define CONFIG_INDEX_SIZE 2
#define CONFIG_INDEX_WEIGHT 3
#define CONFIG_INDEX_TOWINGCAPACITY 4
#define CONFIG_INDEX_OVERRIDENAME 5
#define objectContentsIDD 4000
#define LOG_OCcontents_idc 4001
#define LOG_OCroom_idc 4002
#define LOG_OCtitle_idc 4003
#define LOG_OCpreview_idc 4004
